# Generated by rust2rpm 24
%bcond_without check

%global crate spotifyd

Name:           rust-spotifyd
Version:        0.3.5
Release:        %autorelease
Summary:        Spotify daemon

License:        GPL-3.0-only
URL:            https://crates.io/crates/spotifyd
Source:         %{crates_source}
# Automatically generated patch to strip foreign dependencies
Patch:          spotifyd-fix-metadata-auto.diff

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
A Spotify daemon.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%doc CHANGELOG.md
%doc CONTRIBUTING.md
%doc CONTRIBUTORS.md
%doc README.md
%{_bindir}/spotifyd

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
